### ISSUE TITLE
Script

### ISSUE THREAD

**Issue by Herewulf** [Mavrrick/Hubitat-by-Mavrrick#3]
No signature of method: Script1.definition() is applicable for argument types: (java.util.LinkedHashMap) values: [[name:Govee Integration , namespace:Mavrrick, author:CRAIG KING, ...]] on line 17

**Comment by Mavrrick** [comment]
Are you trying to run this on a Hubitat hub, or something else. This Integration is written specifically for the Hubitat Home Automation platform.
