### ISSUE TITLE
swap devices 

### ISSUE THREAD

**Issue by Fr0s7By7e** [Mavrrick/Hubitat-by-Mavrrick#4]
Hello! I don't think this is really a bug just an issue I ran into.  I recently purchased new Govee light bulbs (H6010) to replace my old ones. I realized that I couldn't just use the Swap Apps Device feature in settings, Guessing it's because Govee devices are children? No idea. So then I tried a hacky way of just changing the device IDs on their device page, which ended up failing because that new device ID isn't getting updated for its device.getDataValue("deviceId"). I've sorta fixed it, however, my background is in javascript so i gave it my best college try. 
I added this to initialize 
```
def initialize(){
	if (device.getDataValue("deviceID") != device.deviceNetworkId) {
        if (debugLog) {log.warn "initialize(): Detected new Device Network Id : ${device.deviceNetworkId}, Applying"}
        newDeviceNetworkId = device.deviceNetworkId.toString()
        updateDeviceInfo(newDeviceNetworkId)
    }
```
    
and then added the code below,  updateDataValue() is complaining about the following key:value pairs - commands, ctMax, and ctMin. not sure what to do about that, tried using updateSetting() but my new devices started working so I couldn't test it. 
    
```
def updateDeviceInfo(newDeviceNetworkId) {

		def params = [
			uri: "https://developer-api.govee.com",
			path: '/v1/devices',
			headers: ["Govee-API-Key": device.getDataValue("apiKey"), "Content-Type": "application/json"],
		]

try {

			httpGet(params) { resp ->
                
				resp.data.data.devices.each {
                    if (debugLog) {log.warn "checking device ${it.device}"}
					deviceID = it.device
					deviceModel = it.model
					deviceName = it.deviceName
					controllable = it.controllable
					retrievable = it.retrievable
					supportCmds = it.supportCmds
					if (newDeviceNetworkId.contains(deviceID)) {
                        if (debugLog) {log.warn "found new device ${deviceID}"}
						device.updateDataValue("deviceID", deviceID)
                        device.updateDataValue("deviceModel", deviceModel)          
                        device.updateSetting("commands", supportCmds)
						if (supportCmds.contains('colorTem') && supportCmds.contains('color')) {
							ctMin = it.properties.colorTem.range.min
							ctMax = it.properties.colorTem.range.max
							device.updateSetting("ctMin", ctMin)
							device.updateSetting("ctMax", ctMax)
						} else if (supportCmds.contains('brightness')) {
							device.updateSetting("ctMin", 'N/A')
							device.updateSetting("ctMax", 'N/A')
						}
					}
              }
          }
	} catch (groovyx.net.http.HttpResponseException e) {
		log.error "Error: e.statusCode ${e.statusCode}"
		log.error "${e}"
		return 'unknown'
	}
}
```
this might all be trash, but a way of swapping devices would be nice! Thanks!

**Comment by Mavrrick** [comment]
There are limitations with using the "Swap App Device" feature of the Hubitat environment. I do believe child devices is part of that.

The idea to do a device swap is interesting and honestly something I haven't put much thought behind. I understand the potential desire for it, but at this point it is so easy to simple install the second device and move your automations over it hasn't been a priority.

My concern is around the whole idea of keeping things in sync between the Govee Cloud API and the integration and minimizing the ability for users to create problems. I will take some time to consider this.

**Comment by Mavrrick** [comment]
With the way the integration has gone in don't think this is a viable option anymore.
