### ISSUE TITLE
Hubitat : Govee - Extract Scene fails

### ISSUE THREAD

**Issue by nyarrow** [Mavrrick/Hubitat-by-Mavrrick#5]
In Hubitat : Govee integration, when I click "Extract Scene", I receive the error below. I tried with both all of my devices remote and all of them local.

(Debug level set to "Trace")

`[app:7](http://192.168.0.208/logs#)2023-12-05 11:14:16.681 AM[error](http://192.168.0.208/logs#)java.lang.NullPointerException: Cannot invoke method get() on null object on line 353 (method sceneExtract)
[app:7](http://192.168.0.208/logs#)2023-12-05 11:14:16.624 AM[debug](http://192.168.0.208/logs#)sceneExtract(): found Default group moving forward
[app:7](http://192.168.0.208/logs#)2023-12-05 11:14:16.167 AM[debug](http://192.168.0.208/logs#)sceneExtract(): Calling HTTP server
[app:7](http://192.168.0.208/logs#)2023-12-05 11:14:16.165 AM[debug](http://192.168.0.208/logs#)sceneExtract() DEVICE INFORMATION`

**Comment by nyarrow** [comment]
Note: The error above occurs when I "Extract Scene" after adding the Govee Home Credentials (which show as "Valid").

**Comment by Mavrrick** [comment]
Based on the code it looks like you don't have the Tap-To-Run's in the location you gave the Hubitat Integration to look for Scenes. Can you make sure you you have a valid tap-to-run with just a scene in it and see if that error continues
